#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour=0
while (( hour <= 12 ))
do
	minute=1
	echo "Hour: $hour"
	while (( minute <= 59 ))
	do
		echo "$minute"
		(( minute++ ))
	done
   	(( hour++ ))
done
